[package]
name = "kalcite-editor"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Éditeur graphique de projets Kalcite"

[[bin]]
name = "kalcite-editor"
path = "src/main.rs"

[dependencies]
eframe = "0.31"
image = { version = "0.25", default-features = false, features = ["png"] }
kalcite-project = { path = "../kalcite-project" }
kalcite-scene = { path = "../kalcite-scene" }
kalcite-linter = { path = "../kalcite-linter" }
kalcite-assets = { path = "../kalcite-assets" }
kalcite-profiler = { path = "../kalcite-profiler" }
