[package]
name = "kalcite-editor"
version = "0.14.0"
edition = "2024"
license = "MIT"
rust-version = "1.88"
description = "Native graphical editor for Kalcite projects"
repository = "https://github.com/Kalcite-Engine/kalcite-editor"

[[bin]]
name = "kalcite-editor"
path = "src/main.rs"

[build-dependencies]
kalcite-syntax = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "4396353aae921851dbe81544361ae75ae5ed41cf" }
kalcite-hir = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "4396353aae921851dbe81544361ae75ae5ed41cf" }
kalcite-mir = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "4396353aae921851dbe81544361ae75ae5ed41cf" }
kalcite-backend-rust = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "4396353aae921851dbe81544361ae75ae5ed41cf" }

[dependencies]
eframe = "0.31"
image = { version = "0.25", default-features = false, features = ["png"] }
kalcite-project = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "4396353aae921851dbe81544361ae75ae5ed41cf" }
kalcite-scene = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "4396353aae921851dbe81544361ae75ae5ed41cf" }
kalcite-linter = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "4396353aae921851dbe81544361ae75ae5ed41cf" }
kalcite-assets = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "4396353aae921851dbe81544361ae75ae5ed41cf" }
kalcite-profiler = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "4396353aae921851dbe81544361ae75ae5ed41cf" }
